window.productionItems = {
            potions: [
                { id: 'p1', name: 'Awaken', effect: 'Removes Silence, Sleep, Calm, Shun, Charm, Fear', productionCost: 4, expiryDate: getOneYearFromTodayDateString(), level: 4, duration: 'Instant' },
                { id: 'p2', name: 'Bless', effect: 'Grants recipient 5 temporary Body Points.', productionCost: 1, expiryDate: getOneYearFromTodayDateString(), level: 1, duration: 'Indefinite' },
                { id: 'p3', name: 'Cause Critical Wounds', effect: '30 points of damage directly to victim\'s Body Points', productionCost: 6, expiryDate: getOneYearFromTodayDateString(), level: 6, duration: 'Instant' },
                { id: 'p4', name: 'Cause Disease', effect: 'Inflicts victim with Disease effect (no running).', productionCost: 3, expiryDate: getOneYearFromTodayDateString(), level: 3, duration: 'Enduring' },
                { id: 'p_light_wounds', name: 'Cause Light Wounds', effect: '5 points of damage directly to victim\'s Body Points', productionCost: 1, expiryDate: getOneYearFromTodayDateString(), level: 1, duration: 'Instant' },
                { id: 'p6', name: 'Cause Mortal Wounds', effect: '40 points of damage directly to victim\'s Body Points', productionCost: 8, expiryDate: getOneYearFromTodayDateString(), level: 8, duration: 'Instant' },
                { id: 'p7', name: 'Cause Serious Wounds', effect: '20 points of damage directly to the Body Points of the victim', productionCost: 4, expiryDate: getOneYearFromTodayDateString(), level: 4, duration: 'Instant' },
                { id: 'p8', name: 'Cause Wounds', effect: '10 points of damage directly to the Body Points of the victim', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), level: 2, duration: 'Instant' },
                { id: 'p9', name: 'Cure Critical Wounds', effect: 'Restores 30 Body Points to recipient\'s body points', productionCost: 6, expiryDate: getOneYearFromTodayDateString(), level: 6, duration: 'Instant' },
                { id: 'p10', name: 'Cure Disease', effect: 'Removes Disease from recipient', productionCost: 3, expiryDate: getOneYearFromTodayDateString(), level: 3, duration: 'Instant' },
                { id: 'p11', name: 'Cure Light Wounds', effect: 'Restores 5 Body Points to recipient', productionCost: 1, expiryDate: getOneYearFromTodayDateString(), level: 1, duration: 'Instant' },
                { id: 'p12', name: 'Cure Mortal Wounds', effect: 'Restores 40 Body Points to the recipient', productionCost: 8, expiryDate: getOneYearFromTodayDateString(), level: 8, duration: 'Instant' },
                { id: 'p13', name: 'Cure Serious Wounds', effect: 'Restores 20 Body Points to the recipient', productionCost: 4, expiryDate: getOneYearFromTodayDateString(), level: 4, duration: 'Instant' },
                { id: 'p14', name: 'Cure Wounds', effect: 'Restores 10 Body Points to the recipient', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), level: 2, duration: 'Instant' },
                { id: 'p15', name: 'Curse', effect: 'All attacks against the victim deal double-damage', productionCost: 7, expiryDate: getOneYearFromTodayDateString(), level: 7, duration: 'Enduring' },
                { id: 'p16', name: 'Dispel Magic', effect: 'Removes all magical effects on the target', productionCost: 8, expiryDate: getOneYearFromTodayDateString(), level: 8, duration: 'Indefinite' },
                { id: 'p17', name: 'Elemental Shield', effect: 'Automatic spell defence against next elemental attack', productionCost: 6, expiryDate: getOneYearFromTodayDateString(), level: 6, duration: 'Indefinite' },
                { id: 'p18', name: 'Magic Armor', effect: 'Automatic spell defence against next physical attack', productionCost: 4, expiryDate: getOneYearFromTodayDateString(), level: 4, duration: 'Indefinite' },
                { id: 'p19', name: 'Purify Blood', effect: 'Removes all Alchemical/poison effects on the recipient', productionCost: 5, expiryDate: getOneYearFromTodayDateString(), level: 5, duration: 'Instant' },
                { id: 'p20', name: 'Reflect Magic', effect: 'Automatic spell defence against next magical attack', productionCost: 8, expiryDate: getOneYearFromTodayDateString(), level: 8, duration: 'Indefinite' },
                { id: 'p21', name: 'Release', effect: 'Frees the target binding effects or held by non-magical means', productionCost: 5, expiryDate: getOneYearFromTodayDateString(), level: 5, duration: 'Instant' },
                { id: 'p22', name: 'Remove Curse', effect: 'Removes the Curse spell/effect', productionCost: 7, expiryDate: getOneYearFromTodayDateString(), level: 7, duration: 'Instant' },
                { id: 'p23', name: 'Remove Drain', effect: 'Removes all active Drain spells or effects', productionCost: 7, expiryDate: getOneYearFromTodayDateString(), level: 7, duration: 'Instant' },
                { id: 'p24', name: 'Remove Physical Affliction', effect: 'Immediately removes any active \'Physical\' effects', productionCost: 6, expiryDate: getOneYearFromTodayDateString(), level: 6, duration: 'Instant' },
                { id: 'p25', name: 'Remove Weakness', effect: 'Removes any active Weakness effects', productionCost: 3, expiryDate: getOneYearFromTodayDateString(), level: 3, duration: 'Instant' },
                { id: 'p26', name: 'Restore Limbs', effect: 'Removes all Withered Limb effects', productionCost: 7, expiryDate: getOneYearFromTodayDateString(), level: 7, duration: 'Instant' },
                { id: 'p27', name: 'Shield Magic', effect: 'Automatic spell defence against next magical effect', productionCost: 5, expiryDate: getOneYearFromTodayDateString(), level: 5, duration: 'Indefinite' },
                { id: 'p28', name: 'Sleep', effect: 'Victim falls into a deep sleep for 5 minutes', productionCost: 6, expiryDate: getOneYearFromTodayDateString(), level: 6, duration: '5-minutes' },
                { id: 'p29', name: 'Taint Blood', effect: 'Victim cannot run or use any in-game skills', productionCost: 5, expiryDate: getOneYearFromTodayDateString(), level: 5, duration: 'Enduring' },
                { id: 'p30', name: 'Unparalyze', effect: 'Removes a Paralyze effect', productionCost: 8, expiryDate: getOneYearFromTodayDateString(), level: 8, duration: 'Instant' },
                { id: 'p31', name: 'Weakness', effect: 'Victim deals 5 points less damage with a weapon', productionCost: 3, expiryDate: getOneYearFromTodayDateString(), level: 3, duration: 'Enduring' },
                { id: 'p32', name: 'Wither Limb', effect: 'Causes a limb to become aged, infirm, and completely useless', productionCost: 7, expiryDate: getOneYearFromTodayDateString(), level: 7, duration: 'Enduring' }
            ],
            scrolls: [
                // Updated Scroll list based on the provided image
                { id: 's_bind', name: 'Bind', productionCost: 4, level: 4, duration: 'Line of Sight', verbal: 'With mystic force I Bind you.', effect: 'Bind victims arms', description: '' },
                { id: 's_destroy', name: 'Destroy', productionCost: 6, level: 6, duration: 'Instant', verbal: 'I summon a force to Destroy <>', effect: 'Causes the targeted item to become useless and unusable. The target may be up to the size of a normal door.', description: '' },
                { id: 's_detect_magic', name: 'Detect Magic', productionCost: 2, level: 2, duration: 'Instant', verbal: 'I call forth mystic power to Detect Magic.', effect: 'Reveals to the caster (and only the caster) if any magic exists on the target.', description: '' },
                { id: 's_elemental_blade', name: 'Elemental Blade', productionCost: 4, level: 4, duration: 'Indefinite', verbal: 'I grant you the power of an Elemental Blade.', effect: 'Allows the recipient to deal five additional points of damage for one attack with a melee weapon.', description: '' },
                { id: 's_enchanted_blade', name: 'Enchanted Blade', productionCost: 6, level: 6, duration: 'Indefinite', verbal: 'I grant you the power of an Enchanted Blade.', effect: 'Changes the damage of a weapon they are wielding to "Magic" damage against a single opponent.', description: '' },
                { id: 's_endow', name: 'Endow', productionCost: 1, level: 1, duration: 'Indefinite', verbal: 'I grant you the power of an Endow.', effect: 'Allows recipient to deal two additional points of damage for next attack with a melee weapon', description: '' },
                { id: 's_guardian_of_the_four', name: 'Guardian of the Four', productionCost: 7, level: 7, duration: 'Indefinite', verbal: 'I grant you the power of a <fire, ice, lightning or stone> Shield.', effect: 'Bestows the recipient with a specific automatic Spell Defense of the type desired by the caster.', description: '' },
                { id: 's_shatter', name: 'Shatter', productionCost: 3, level: 3, duration: 'Instant', verbal: 'I summon a force to Shatter <item>', effect: 'Causes targeted hand-held item to become useless and unusable. Up to the size of a shield.', description: '' },
                { id: 's_silver_aura', name: 'Silver Aura', productionCost: 5, level: 5, duration: 'Indefinite', verbal: 'I grant you the power of a Silver Aura.', effect: 'Alter damage type of one weapon to \'Silver\' damage', description: '' },
                // Retained existing scrolls not in the new image to avoid accidental deletion
                { id: 's_elemental_shield', name: 'Elemental Shield', productionCost: 6, level: 6, duration: 'Indefinite', verbal: 'I grant you the power of an Elemental Shield.', effect: 'Automatic spell defence against next elemental attack', description: '' },
                { id: 's_reflect_magic', name: 'Reflect Magic', productionCost: 8, level: 8, duration: 'Indefinite', verbal: 'I call forth mystic power to Reflect Magic.', effect: 'Automatic spell defence against next magical attack', description: '' },
                { id: 's_shield', name: 'Shield', productionCost: 1, level: 1, duration: 'Indefinite', verbal: 'With eldritch force I grant you a Shield 5.', effect: 'Grants 5 armour', description: '' },
                { id: 's_magic_armor', name: 'Magic Armor', productionCost: 4, level: 2, duration: 'Indefinite', verbal: 'I grant you the power of a Magic Armor.', effect: 'Automatic spell defence against next physical attack', description: '' },
                { id: 's_release', name: 'Release', productionCost: 5, level: 5, duration: 'Instant', verbal: 'With mystic force I Release you.', effect: 'Frees the target binding effects or held by non-magical means', description: '' },
                { id: 's_dispel_magic', name: 'Dispel Magic', productionCost: 8, level: 8, duration: 'Instant', verbal: 'I call forth mystic power to Dispel Magic.', effect: 'Removes all magical effects on the target', description: '' },
                { id: 's_awaken', name: 'Awaken', productionCost: 4, level: 4, duration: 'Instant', verbal: 'I command you to Awaken.', effect: 'Removes Silence, Sleep, Calm, Shun, Charm, Fear', description: '' },
                { id: 's_delayed_endow', name: 'Delayed Endow', productionCost: 2, level: 2, duration: 'Indefinite', verbal: 'I grant you the power of a Delayed Endow.', effect: 'Two additional points of damage with melee weapon - One attack. May be expended to Rip and Pin and Bind effects', description: '' },
                { id: 's_dragons_breath', name: 'Dragon\'s Breath', productionCost: 8, level: 8, duration: 'Instant', verbal: 'I call forth a Dragon\'s Breath 40.', effect: 'Deals 40 points of damage to the target.', description: '' },
                { id: 's_fumble', name: 'Fumble', productionCost: 1, level: 1, duration: '5-seconds', verbal: 'I summon a force to Fumble your <>', effect: 'Causes one item held by the victim to become unusable for 5-seconds.', description: '' },
                { id: 's_flame_bolt', name: 'Flame Bolt', productionCost: 4, level: 4, duration: 'Instant', verbal: 'I call forth a Flame Bolt 20.', effect: 'Deals 20 points of damage to the target.', description: '' },
                { id: 's_ice_bolt', name: 'Ice Bolt', productionCost: 3, level: 7, duration: 'Instant', verbal: 'I call forth an Ice Bolt 15.', effect: 'Deals 15 points of damage to the target.', description: '' },
                { id: 's_ice_storm', name: 'Ice Storm', productionCost: 7, level: 7, duration: 'Instant', verbal: 'I call forth an Ice Storm 35.', effect: 'Deals 35 points of damage to the target.', description: '' },
                { id: 's_lightning_bolt', name: 'Lightning Bolt', productionCost: 2, level: 2, duration: 'Instant', verbal: 'I call forth a Lightning Bolt 10.', effect: 'Deals 10 points of damage to the target.', description: '' },
                { id: 's_lightning_storm',  name: 'Lightning Storm', productionCost: 6, level: 6, duration: 'Instant', verbal: 'I call forth a Lightning Storm 30.', effect: 'Deals 30 points of damage to the target.', description: '' },
                { id: 's_magic_missile', name: 'Magic Missile', productionCost: 1, level: 1, duration: 'Instant', verbal: 'I call forth a Magic Missile 5.', effect: 'Deals 5 points of damage to the target.', description: '' },
                { id: 's_pin', name: 'Pin', productionCost: 2, level: 2, duration: 'Line of Sight', verbal: 'With mystic force I Pin you.', effect: 'This binding spell immediately forces the right foot of the victim to be fixed in place.', description: '' },
                { id: 's_repel', name: 'Repel', productionCost: 2, level: 2, duration: 'Concentration', verbal: 'With mystic force I Repel you.', effect: 'Creates a force which pushes the victim away from the caster so they are ten-feet away and prevents victim and caster from moving any closer to each other', description: '' },
                { id: 's_shield_magic', name: 'Shield Magic', productionCost: 5, level: 5, duration: 'Indefinite', verbal: 'I call forth mystic power to Shield Magic.', effect: 'Bestows an automatic Spell Defense triggered by a Spellstrike, or magical effect.', description: '' },
                { id: 's_shun', name: 'Shun', productionCost: 4, level: 4, duration: '5-minutes', verbal: 'I command you to Shun me.', effect: 'The victim will not attack the caster, must immediately move to a distance of ten feet, and will stay at least ten feet away.', description: '' },
                { id: 's_sleep', name: 'Sleep', productionCost: 6, level: 6, duration: '5-minutes', verbal: 'I command you to Sleep.', effect: 'Causes victim to fall into a deep sleep for the duration', description: '' },
                { id: 's_stone_bolt', name: 'Stone Bolt', productionCost: 5, level: 5, duration: 'Instant', verbal: 'I call forth a Stone Bolt 25.', effect: 'Deals 25 points of damage to the target.', description: '' },
                { id: 's_web', name: 'Web', productionCost: 5, level: 5, duration: 'Line of Sight', verbal: 'With mystic force I Web you.', effect: 'Forces arms of victim straight down to their sides and completely immobilizes entire body.', description: '' },
            ],
            alchemy: [
                { id: 'a_alchemical_solvent', name: 'Alchemical Solvent', description: 'This Alchemy removes an Oil of Slipperiness or a Paste of Stickiness from an area up to one square foot.', type: 'Contact', duration: 'Instant', effect: 'Removes Oil of Slipperiness or Paste of Stickiness', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_antidote_contact', name: 'Antidote (Contact)', description: 'An Antidote is a cure for a specific type of Alchemical effect The proper Antidote must be used to remove the effect and is based on the Alchemy Delivery Method (Ingested, Gas, Contact) Antidote does not affect Carrier Attacks or any effects which are not Alchemical, even if they duplicate an Alchemy effect.', type: 'Contact', duration: 'Instant', effect: 'Antidote for contact poisons', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_antidote_gas', name: 'Antidote (Gas)', description: 'An Antidote is a cure for a specific type of Alchemical effect The proper Antidote must be used to remove the effect and is based on the Alchemy Delivery Method (Ingested, Gas, Contact) Antidote does not affect Carrier Attacks or any effects which are not Alchemical, even if they duplicate an Alchemy effect.', type: 'Gas', duration: 'Instant', effect: 'Antidote for Gas Poisons', productionCost: 4, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_antidote_ingested', name: 'Antidote (Ingested)', description: 'An Antidote is a cure for a specific type of Alchemical effect The proper Antidote must be used to remove the effect and is based on the Alchemy Delivery Method (Ingested, Gas, Contact) Antidote does not affect Carrier Attacks or any effects which are not Alchemical, even if they duplicate an Alchemy effect.', type: 'Elixir', duration: 'Instant', effect: 'Antidote for Ingested Poison', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_berserk', name: 'Berserk', description: 'This effect causes the victim to enter a mindless killing frenzy. While under the effects, the victim will attack any creatures or characters they can see, to the best of their ability (including melee, spells, gas globes, etc.) for the duration of the effect, regardless of the target being friend or foe. Berserk is not a Charm-Group effect. This effect is removed by Purify Blood.', type: 'Elixir', duration: '5 Minutes', effect: 'Victim enters a mindless killing frenzy', productionCost: 10, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_cause_damage', name: 'Cause Damage', description: 'The victim suffers 10 points of damage directly to their Body Points.', type: 'Elixir', duration: 'Instant', effect: '10 damage directly to Body', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_cause_damage', name: 'Cause Damage', description: 'The victim suffers 10 points of damage directly to their Body Points.', type: 'Gas', duration: 'Instant', effect: '10 damage directly to Body', productionCost: 3, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_cause_light_damage', name: 'Cause Light Damage', description: 'The victim suffers 5 points of damage directly to their Body Points.', type: 'Elixir', duration: 'Instant', effect: '5 damage directly to Body', productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_cause_light_damage', name: 'Cause Light Damage', description: 'The victim suffers 5 points of damage directly to their Body Points.', type: 'Gas', duration: 'Instant', effect: '5 damage directly to Body', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_cause_serious_damage', name: 'Cause Serious Damage', description: 'The victim suffers 20 points of damage directly to their Body Points.', type: 'Elixir', duration: 'Instant', effect: '20 damage directly to Body', productionCost: 4, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_cause_serious_damage', name: 'Cause Serious Damage', description: 'The victim suffers 20 points of damage directly to their Body Points.', type: 'Gas', duration: 'Instant', effect: '20 damage directly to Body', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_charm', name: 'Charm', description: 'A Charm effect which alters the behavior of the victim so they view the alchemist as their â€œbest friendâ€ for the duration of the effect. The victim may not be convinced in any way or by any means that they have been Charmed or that the caster is not their best friend. The victim will not make any attempt to remove this spell and will be completely unaware of the casting of the Charm spell until is wears off or is removed. The victim must stay near the side of the caster and listen to the â€œsuggestionsâ€ of their â€œbest friendâ€. They will not mindlessly obey orders or commands issued which are contrary to their nature, but might be convinced into doing such things by the caster (if they are cleaver enough). The victim must be able to understand the caster and speak the same language in order for the caster to convey their â€œsuggestionsâ€. Certain creatures designated as â€œmindlessâ€ (such as lesser undead) or other creatures such as Golems or insects either donâ€™t have a mind or have a hive-mind, which the Charm spell cannot target, causing them to be immune (their monster card will determine if they are). If the victim is attacked by characters siding with the caster (the casterâ€™s party members), the victim will question why the caster is not stopping them. If insufficient reason are provided (or none at all), the effect might be broken (this is decided by the player of the victim). The effect immediately expires if the victim is attacked by the caster directly. Once the Charm is broken or expires, the victim will no longer be under the effects of the Charm and will remember everything except the casting of the Charm spell. They might still not realize they were Charmed however, depending of the situation. This spell is more powerful than a Calm or Shun effects in the Charm-Group, but less-powerful than Control Undead, Fear, Vampire Charm, or Enslavement in the Charm Group hierarchy (see Charm Effects on page 41).', type: 'Gas', duration: '5 Minutes', effect: 'Victim is now your best friend', productionCost: 8, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_cure_light_damage', name: 'Cure Light Damage', description: 'This effect restores 5 Body Points to the recipient, up to their maximum Body Points. Unconscious or Dying characters will be restored but it will not affect a dead character (because they need a Life spell).', type: 'Elixir', duration: 'Instant', effect: 'Restores 5 Body points', productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_death', name: 'Death', description: 'This elixir immediately causes the death of the victim, reducing them to -1 Body Points and the Dead state. The victim must receive a Life spell within 5-minutes or they will resurrect (see Life & Death on page 14).', type: 'Elixir', duration: 'Instant', effect: 'Immediate death of the victim', productionCost: 9, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_enslavement_antidote', name: 'Enslavement Antidote', description: 'This effect removes all Enslavement effects on the character. The character remembers everything during the time Enslaved and knows who they were Enslaved to. If the character was also affected by a Forget-It-Well or Forget- Me-Not, they will still not remember anything during that time.', type: 'Elixir', duration: 'Instant', effect: 'Removes Enslavement effect', productionCost: 10, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_feeblemind', name: 'Feeblemind', description: 'The victimâ€™s intelligence is reduced to that of an idiot, causing them to be unable to use any in-game skills for the duration of the effect. The character will not be aware they were under the effects of Feeblemind, even after the effect ends or they are cured.', type: 'Elixir', duration: '5 Minutes', effect: 'Victim becomes an idiot. No in-game skills', productionCost: 6, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_feeblemind', name: 'Feeblemind', description: 'The victimâ€™s intelligence is reduced to that of an idiot, causing them to be unable to use any in-game skills for the duration of the effect. The character will not be aware they were under the effects of Feeblemind, even after the effect ends or they are cured.', type: 'Gas', duration: '5 Minutes', effect: 'Victim becomes an idiot. No in-game skills', productionCost: 7, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_forget_it_well', name: 'Forget-it-well', description: 'The victim suffers complete amnesia, forgetting everything which happened in the past hour, there is a blank spot where the memories once were. The victim will not immediately be aware of the blank spot in their memory, but circumstances might arise which cause them to question the gaps and reach the conclusion they were poisoned. The effect may be removed within the first ten-minutes of delivery if the character receives an Antidote: Ingested or a Purify Blood. The amnesia becomes permanent if not cured within ten-minutes of delivery, after which nothing will restore the lost memories (including Resurrection). If the victimâ€™s body dissipates before the ten-minute time period, the Forget-It-Well effect is negated and the characterâ€™s memories are restored. Forget-It-Well cannot be used on a dead character (neither can any other poison)', type: 'Elixir', duration: 'Enduring', effect: 'Amnesia regarding the last hour', productionCost: 10, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_forget_me_not', name: 'Forget-me-not', description: 'This effect functions identically to Forget-It-Well (above), except the memory loss is everything in the last fifteen minutes (instead of one-hour).', type: 'Elixir', duration: 'Enduring', effect: 'Amnesia regarding the last 15 minutes', productionCost: 7, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_hallucinoid', name: 'Hallucinoid', description: 'This effect causes the victim to hallucinate and see things which are not actually there, for the duration of the effect. The victim might be aware they are poisoned but will not be able to ignore the effects even if they know they are not real. The character retains all abilities and skills, but is likely to use them against the hallucinations. The player should roleplay the effects of seeing strange things while the character is under the effects of this poison.', type: 'Elixir', duration: '5 Minutes', effect: 'Victim hallucinates', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_intoxicant', name: 'Intoxicant', description: 'The character becomes extremely drunk for the duration of the effect, as if they consumed a strong alcoholic drink. This has no other in-game effect and the character retains all abilities and skills.', type: 'Elixir', duration: '1 Hour', effect: 'Victim becomes extremely drunk', productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_liquid_light', name: 'Liquid Light', description: 'This effect functions exactly like the spell Illumination, except it is non-magical in nature. In order to use a Liquid Light Alchemy, the character must have at least Alchemy Level 1, but once activated, it can be given to another character to use. A Liquid Light is not affected by a Dispel Magic but is destroyed if affected by a Shatter or Destroy effect or an Alchemical Solvent.', type: 'Contact', duration: '5 Days', effect: 'Illuminates an object (non-magical effect)', productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_nausea', name: 'Nausea', description: 'This effect causes the victim to become nauseous and fell ill, causing them to be unable to use any in-game skills for the duration of the effect.', type: 'Elixir', duration: '5 Minutes', effect: 'Victim becomes nauseous. No in-game skills', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_nausea', name: 'Nausea', description: 'This effect causes the victim to become nauseous and fell ill, causing them to be unable to use any in-game skills for the duration of the effect.', type: 'Gas', duration: '5 Minutes', effect: 'Victim becomes nauseous. No in-game skills', productionCost: 6, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_oil_of_slipperiness', name: 'Oil of Slipperiness', description: 'One dose of this slippery substance will affect an area up to one square foot or one hand-held object. If spread on the ground, it will prevent any character from standing in that area, or even to crawl out of the area without help or something to hold on to. If spread on a hand-help object, the object becomes impossible to hold or even pick up. Multiple doses may be used to cover larger areas or bigger objects. An Alchemical Solvent or a Paste of Stickiness will remove the effect (larger areas will require more doses).', type: 'Contact', duration: '1 Hour', effect: 'Surface becomes extremely slippery', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_paralyze', name: 'Paralyze', description: 'This elixir affects the victim so they are unable to move any part of their body or even speak. The victim must have a metabolism for this spell to affect them. The victim is helpless (but not incapacitated) and is unable to prevent being searched or issued a Killing Blow. If the victim is moved by an outside force (such as by another character), is knocked unconscious, or is affected by Sleep, they will collapse to the ground, but the Paralyze effect will remain active. The effect ends if the victim receives a Remove Curse, Unparalyze, or Dispel Magic; this effect is not removed by Release.', type: 'Elixir', duration: '5 Minutes', effect: 'Victim is unable to move any part of their body', productionCost: 8, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_paralyze', name: 'Paralyze', description: 'This gas affects the victim so they are unable to move any part of their body or even speak. The victim must have a metabolism for this spell to affect them. The victim is helpless (but not incapacitated) and is unable to prevent being searched or issued a Killing Blow. If the victim is moved by an outside force (such as by another character), is knocked unconscious, or is affected by Sleep, they will collapse to the ground, but the Paralyze effect will remain active. The effect ends if the victim receives a Remove Curse, Unparalyze, or Dispel Magic; this effect is not removed by Release.', type: 'Gas', duration: '5 Minutes', effect: 'Victim is unable to move any part of their body', productionCost: 9, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_paranoia', name: 'Paranoia', description: 'This effect causes the victim to be completely convinced people they normally dislike are in fact out to kill them. Paranoia is not a Charm effect.', type: 'Elixir', duration: '5 Minutes', effect: 'Theyâ€™re out to get you', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_paranoia', name: 'Paranoia', description: 'This effect causes the victim to be completely convinced people they normally dislike are in fact out to kill them. Paranoia is not a Charm effect.', type: 'Gas', duration: '5 Minutes', effect: 'Theyâ€™re out to get you', productionCost: 3, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_past_of_stickiness', name: 'Past of Stickiness', description: 'One dose of this sticky substance will affect an area up to one square inch or one hand-held object. If spread on the ground, it will act as a Pin effect to any character standing in that area. If spread on a hand-help object, the object becomes impossible to drop and will stick to the character. Multiple doses may be used to cover larger areas or bigger objects. An Alchemical Solvent or an Oil of Slipperiness will remove the effect (larger areas will require more doses). A Release spell will also remove the effect.', type: 'Contact', duration: '1 Hour', effect: 'Makes things very sticky! One square inch', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_poison_shield', name: 'Poison Shield', description: 'This elixir bestows upon the recipient an automatic Defense which is triggered by any attack with the word â€œPoisonâ€ in the delivery phrase, regardless of the delivery method, which hits them. When triggered, the Poison Shield is expended, negating the attack. If the character is aware they are consuming an Elixir, they may â€œacceptâ€ the effect in the same way they accept a touchcast spell, allowing the elixir to bypass the defense. If they donâ€™t accept the effect, the Poison Shield is triggered normally. The character may choose to use Cloak, Bane, or Dodge before Poison Shield, but may not use Resist or Return. The player must state the out-of-game verbal phrase â€œPoison Shieldâ€ within three-seconds of being affected. See Spell Defenses on page 41 for more information on these rules.', type: 'Elixir', duration: 'Indefinite', effect: 'Automatic Defense triggered by poison attacks', productionCost: 4, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_sleep', name: 'Sleep', description: 'This elixir immediately causes the victim to fall into a deep sleep for the duration of the effect. The effect is removed if the victim is affected by an Awaken or if another character forcefully shakes them while shouting loudly for one minute (remember the Body Contact rule).', type: 'Elixir', duration: '5 Minutes', effect: 'Nap time', productionCost: 6, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_sleep', name: 'Sleep', description: 'This gas immediately causes the victim to fall into a deep sleep for the duration of the effect. The effect is removed if the victim is affected by an Awaken or if another character forcefully shakes them while shouting loudly for one minute (remember the Body Contact rule).', type: 'Gas', duration: '5 Minutes', effect: 'Nap time', productionCost: 7, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_vertigo', name: 'Vertigo', description: 'This effect causes the victim to become dizzy and unable to stand, causing them to be unable to use any in-game skills for the duration of the effect.', type: 'Elixir', duration: '5 Minutes', effect: 'Victim is dizzy and cannot stand. No in-game skills', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_vertigo', name: 'Vertigo', description: 'This effect causes the victim to become dizzy and unable to stand, causing them to be unable to use any in-game skills for the duration of the effect.', type: 'Gas', duration: '5 Minutes', effect: 'Victim is dizzy and cannot stand. No in-game skills', productionCost: 6, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_vorpal_coating_1', name: 'Vorpal Coating 1', description: 'This weapon coating increases the damage dealt by a weapon it is applied to by five points for a specified number of hits. Vorpal Coating 1 (one hit), Vorpal Coating 3 (three hits), and Vorpal Coating 5 (five hits). See Vorpal Coatings on page 111 for additional information.', type: 'Contact', duration: 'Indefinite', effect: 'Adds 5 points to weapon damage for 1 hit', productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_vorpal_coating_3', name: 'Vorpal Coating 3', description: 'This weapon coating increases the damage dealt by a weapon it is applied to by five points for a specified number of hits. Vorpal Coating 1 (one hit), Vorpal Coating 3 (three hits), and Vorpal Coating 5 (five hits). See Vorpal Coatings on page 111 for additional information.', type: 'Contact', duration: 'Indefinite', effect: 'Adds 5 points to weapon damage for 3 hits', productionCost: 3, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_vorpal_coating_5', name: 'Vorpal Coating 5', description: 'This weapon coating increases the damage dealt by a weapon it is applied to by five points for a specified number of hits. Vorpal Coating 1 (one hit), Vorpal Coating 3 (three hits), and Vorpal Coating 5 (five hits). See Vorpal Coatings on page 111 for additional information.', type: 'Contact', duration: 'Indefinite', effect: 'Adds 5 points to weapon damage for 5 hits', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_weakness', name: 'Weakness', description: 'This elixir immediately causes the victim to deal five points less damage with a weapon (minimum of zero) for the duration of the effect. All weapon damage dealt by the victim is affected regardless of type or hand. This effect does not reduce the strength of the victim, only the damage they are able to deal.', type: 'Elixir', duration: '5 Minutes', effect: 'Victim causes 5 less damage with a weapon', productionCost: 3, expiryDate: getOneYearFromTodayDateString() },
                { id: 'a_weakness', name: 'Weakness', description: 'This gas immediately causes the victim to deal five points less damage with a weapon (minimum of zero) for the duration of the effect. All weapon damage dealt by the victim is affected regardless of type or hand. This effect does not reduce the strength of the victim, only the damage they are able to deal.', type: 'Gas', duration: '5 Minutes', effect: 'Victim causes 5 less damage with a weapon', productionCost: 4, expiryDate: getOneYearFromTodayDateString() }
            ],
            refinedMaterials: [
                { id: 'rm1', name: 'Alchemy Materials', value: 10, productionCost: 10 },
                { id: 'rm2', name: 'Potion Making Materials', value: 10, productionCost: 10 },
                { id: 'rm3', name: 'Scroll Making Materials', value: 10, productionCost: 10 },
                { id: 'rm4', name: 'Rune Making Materials', value: 10, productionCost: 10 },
                { id: 'rm5', name: 'Smithing Materials', value: 10, productionCost: 10 },
                { id: 'rm6', name: 'Shatter Resist Component', value: 1, productionCost: 1 } 
            ],
            // New Categories
            weapons: [
                { id: 'w1', name: 'Bludgeon', productionCost: 1, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w2', name: 'Bow', productionCost: 4, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w3', name: 'Crossbow', productionCost: 4, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w4', name: 'Dagger', productionCost: 1, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w5', name: 'Hatchet', productionCost: 1, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w6', name: 'Javelin', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w7', name: 'Long Axe', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w8', name: 'Long Hammer', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w9', name: 'Long Mace', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w10', name: 'Long Sword', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w11', name: 'Polearm', productionCost: 4, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w12', name: 'Quiver (Arrows/Bolts, 30)', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w13', name: 'Sap', productionCost: 1, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w14', name: 'Shield', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w15', name: 'Short Axe', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w16', name: 'Short Hammer', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w17', name: 'Short Mace', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w18', name: 'Short Sword', productionCost: 2, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w19', name: 'Spear', productionCost: 3, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w20', name: 'Staff', productionCost: 1, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w21', name: 'Throwing Dagger', productionCost: 1, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w22', name: 'Two-Handed Blunt', productionCost: 4, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' },
                { id: 'w23', name: 'Two-Handed Sword', productionCost: 4, expiryDate: getOneYearFromTodayDateString(), material: 'Steel' }
            ],
            armour: [
                { id: 'ar1', name: 'Helm', material: 'Plate', armourValue: 3, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar2', name: 'Chest Armour', material: 'Plate', armourValue: 9, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar3', name: 'Back Armour', material: 'Plate', armourValue: 9, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar4', name: 'Shoulder/ Upper Arm Armour (L+R)', material: 'Plate', armourValue: 6, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar5', name: 'Forearm Armour (L+R)', material: 'Plate', armourValue: 6, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar6', name: 'Thigh Armour (L+R)', material: 'Plate', armourValue: 6, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar7', name: 'Leg Armour (L+R)', material: 'Plate', armourValue: 6, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar8', name: 'Helm', material: 'Chain', armourValue: 2, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar9', name: 'Chest Armour', material: 'Chain', armourValue: 6, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar10', name: 'Back Armour', material: 'Chain', armourValue: 6, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar11', name: 'Shoulder/ Upper Arm Armour (L+R)', material: 'Chain', armourValue: 4, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar12', name: 'Forearm Armour (L+R)', material: 'Chain', armourValue: 4, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar13', name: 'Thigh Armour (L+R)', material: 'Chain', armourValue: 4, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar14', name: 'Leg Armour (L+R)', material: 'Chain', armourValue: 4, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar15', name: 'Helm', material: 'Leather', armourValue: 1, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar16', name: 'Chest Armour', material: 'Leather', armourValue: 3, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar17', name: 'Back Armour', material: 'Leather', armourValue: 3, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar18', name: 'Shoulder/ Upper Arm Armour (L+R)', material: 'Leather', armourValue: 2, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar19', name: 'Forearm Armour (L+R)', material: 'Leather', armourValue: 2, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar20', name: 'Thigh Armour (L+R)', material: 'Leather', armourValue: 2, productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 'ar21', name: 'Leg Armour (L+R)', material: 'Leather', armourValue: 2, productionCost: 1, expiryDate: getOneYearFromTodayDateString() }
            ],
            traps: [
                { id: 't1', name: 'Acid trap 10', productionCost: 10, expiryDate: getOneYearFromTodayDateString() },
                { id: 't2', name: 'Acid trap 12', productionCost: 12, expiryDate: getOneYearFromTodayDateString() },
                { id: 't3', name: 'Acid trap 14', productionCost: 14, expiryDate: getOneYearFromTodayDateString() },
                { id: 't4', name: 'Acid trap 16', productionCost: 16, expiryDate: getOneYearFromTodayDateString() },
                { id: 't5', name: 'Acid trap 18', productionCost: 18, expiryDate: getOneYearFromTodayDateString() },
                { id: 't6', name: 'Acid trap 2', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 't7', name: 'Acid trap 20', productionCost: 20, expiryDate: getOneYearFromTodayDateString() },
                { id: 't8', name: 'Acid trap 22', productionCost: 22, expiryDate: getOneYearFromTodayDateString() },
                { id: 't9', name: 'Acid trap 24', productionCost: 24, expiryDate: getOneYearFromTodayDateString() },
                { id: 't10', name: 'Acid trap 4', productionCost: 4, expiryDate: getOneYearFromTodayDateString() },
                { id: 't11', name: 'Acid trap 6', productionCost: 6, expiryDate: getOneYearFromTodayDateString() },
                { id: 't12', name: 'Acid trap 8', productionCost: 8, expiryDate: getOneYearFromTodayDateString() },
                { id: 't13', name: 'Alarms/Noisemakers', productionCost: 1, expiryDate: getOneYearFromTodayDateString() },
                { id: 't14', name: 'Explosive trap 15', productionCost: 15, expiryDate: getOneYearFromTodayDateString() },
                { id: 't15', name: 'Explosive trap 17', productionCost: 17, expiryDate: getOneYearFromTodayDateString() },
                { id: 't16', name: 'Explosive trap 19', productionCost: 19, expiryDate: getOneYearFromTodayDateString() },
                { id: 't17', name: 'Explosive trap 21', productionCost: 21, expiryDate: getOneYearFromTodayDateString() },
                { id: 't18', name: 'Explosive trap 23', productionCost: 23, expiryDate: getOneYearFromTodayDateString() },
                { id: 't19', name: 'Explosive trap 25', productionCost: 25, expiryDate: getOneYearFromTodayDateString() },
                { id: 't20', name: 'Explosive trap 27', productionCost: 27, expiryDate: getOneYearFromTodayDateString() },
                { id: 't21', name: 'Explosive trap 29', productionCost: 29, expiryDate: getOneYearFromTodayDateString() },
                { id: 't22', name: 'Explosive trap 30', productionCost: 30, expiryDate: getOneYearFromTodayDateString() },
                { id: 't23', name: 'Fire trap 10', productionCost: 10, expiryDate: getOneYearFromTodayDateString() },
                { id: 't24', name: 'Fire trap 12', productionCost: 12, expiryDate: getOneYearFromTodayDateString() },
                { id: 't25', name: 'Fire trap 14', productionCost: 14, expiryDate: getOneYearFromTodayDateString() },
                { id: 't26', name: 'Fire trap 16', productionCost: 16, expiryDate: getOneYearFromTodayDateString() },
                { id: 't27', name: 'Fire trap 17', productionCost: 17, expiryDate: getOneYearFromTodayDateString() },
                { id: 't28', name: 'Fire trap 18', productionCost: 18, expiryDate: getOneYearFromTodayDateString() },
                { id: 't29', name: 'Fire trap 2', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 't30', name: 'Fire trap 20', productionCost: 20, expiryDate: getOneYearFromTodayDateString() },
                { id: 't31', name: 'Fire trap 4', productionCost: 4, expiryDate: getOneYearFromTodayDateString() },
                { id: 't32', name: 'Fire trap 6', productionCost: 6, expiryDate: getOneYearFromTodayDateString() },
                { id: 't33', name: 'Fire trap 8', productionCost: 8, expiryDate: getOneYearFromTodayDateString() },
                { id: 't34', name: 'Gas trap 10', productionCost: 10, expiryDate: getOneYearFromTodayDateString() },
                { id: 't35', name: 'Gas trap 12', productionCost: 12, expiryDate: getOneYearFromTodayDateString() },
                { id: 't36', name: 'Gas trap 13', productionCost: 13, expiryDate: getOneYearFromTodayDateString() },
                { id: 't37', name: 'Gas trap 14', productionCost: 14, expiryDate: getOneYearFromTodayDateString() },
                { id: 't38', name: 'Gas trap 15', productionCost: 15, expiryDate: getOneYearFromTodayDateString() },
                { id: 't39', name: 'Gas trap 16', productionCost: 16, expiryDate: getOneYearFromTodayDateString() },
                { id: 't40', name: 'Gas trap 18', productionCost: 18, expiryDate: getOneYearFromTodayDateString() },
                { id: 't41', name: 'Gas trap 2', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 't42', name: 'Gas trap 20', productionCost: 20, expiryDate: getOneYearFromTodayDateString() },
                { id: 't43', name: 'Gas trap 3', productionCost: 3, expiryDate: getOneYearFromTodayDateString() },
                { id: 't44', name: 'Gas trap 4', productionCost: 4, expiryDate: getOneYearFromTodayDateString() },
                { id: 't45', name: 'Gas trap 5', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 't46', name: 'Gas trap 6', productionCost: 6, expiryDate: getOneYearFromTodayDateString() },
                { id: 't47', name: 'Gas trap 8', productionCost: 8, expiryDate: getOneYearFromTodayDateString() },
                { id: 't48', name: 'Massive mechanical trap 10', productionCost: 10, expiryDate: getOneYearFromTodayDateString() },
                { id: 't49', name: 'Massive mechanical trap 11', productionCost: 11, expiryDate: getOneYearFromTodayDateString() },
                { id: 't50', name: 'Massive mechanical trap 12', productionCost: 12, expiryDate: getOneYearFromTodayDateString() },
                { id: 't51', name: 'Massive mechanical trap 13', productionCost: 13, expiryDate: getOneYearFromTodayDateString() },
                { id: 't52', name: 'Massive mechanical trap 14', productionCost: 14, expiryDate: getOneYearFromTodayDateString() },
                { id: 't53', name: 'Massive mechanical trap 15', productionCost: 15, expiryDate: getOneYearFromTodayDateString() },
                { id: 't54', name: 'Massive mechanical trap 16', productionCost: 16, expiryDate: getOneYearFromTodayDateString() },
                { id: 't55', name: 'Massive mechanical trap 17', productionCost: 17, expiryDate: getOneYearFromTodayDateString() },
                { id: 't56', name: 'Massive mechanical trap 18', productionCost: 18, expiryDate: getOneYearFromTodayDateString() },
                { id: 't57', name: 'Massive mechanical trap 19', productionCost: 19, expiryDate: getOneYearFromTodayDateString() },
                { id: 't58', name: 'Massive mechanical trap 20', productionCost: 20, expiryDate: getOneYearFromTodayDateString() },
                { id: 't59', name: 'Massive mechanical trap 2', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 't60', name: 'Massive mechanical trap 3', productionCost: 3, expiryDate: getOneYearFromTodayDateString() },
                { id: 't61', name: 'Massive mechanical trap 4', productionCost: 4, expiryDate: getOneYearFromTodayDateString() },
                { id: 't62', name: 'Massive mechanical trap 5', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 't63', name: 'Massive mechanical trap 6', productionCost: 6, expiryDate: getOneYearFromTodayDateString() },
                { id: 't64', name: 'Massive mechanical trap 7', productionCost: 7, expiryDate: getOneYearFromTodayDateString() },
                { id: 't65', name: 'Massive mechanical trap 8', productionCost: 8, expiryDate: getOneYearFromTodayDateString() },
                { id: 't66', name: 'Massive mechanical trap 9', productionCost: 9, expiryDate: getOneYearFromTodayDateString() },
                { id: 't67', name: 'Weapon trap 10', productionCost: 10, expiryDate: getOneYearFromTodayDateString() },
                { id: 't68', name: 'Weapon trap 12', productionCost: 12, expiryDate: getOneYearFromTodayDateString() },
                { id: 't69', name: 'Weapon trap 13', productionCost: 13, expiryDate: getOneYearFromTodayDateString() },
                { id: 't70', name: 'Weapon trap 14', productionCost: 14, expiryDate: getOneYearFromTodayDateString() },
                { id: 't71', name: 'Weapon trap 15', productionCost: 15, expiryDate: getOneYearFromTodayDateString() },
                { id: 't72', name: 'Weapon trap 16', productionCost: 16, expiryDate: getOneYearFromTodayDateString() },
                { id: 't73', name: 'Weapon trap 18', productionCost: 18, expiryDate: getOneYearFromTodayDateString() },
                { id: 't74', name: 'Weapon trap 19', productionCost: 19, expiryDate: getOneYearFromTodayDateString() },
                { id: 't75', name: 'Weapon trap 2', productionCost: 2, expiryDate: getOneYearFromTodayDateString() },
                { id: 't76', name: 'Weapon trap 20', productionCost: 20, expiryDate: getOneYearFromTodayDateString() },
                { id: 't77', name: 'Weapon trap 3', productionCost: 3, expiryDate: getOneYearFromTodayDateString() },
                { id: 't78', name: 'Weapon trap 4', productionCost: 4, expiryDate: getOneYearFromTodayDateString() },
                { id: 't79', name: 'Weapon trap 5', productionCost: 5, expiryDate: getOneYearFromTodayDateString() },
                { id: 't80', name: 'Weapon trap 6', productionCost: 6, expiryDate: getOneYearFromTodayDateString() },
                { id: 't81', name: 'Weapon trap 7', productionCost: 7, expiryDate: getOneYearFromTodayDateString() },
                { id: 't82', name: 'Weapon trap 8', productionCost: 8, expiryDate: getOneYearFromTodayDateString() },
                { id: 't83', name: 'Weapon trap 9', productionCost: 9, expiryDate: getOneYearFromTodayDateString() }
            ],
            runicTattoos: [], // This will be populated from CSV
            formalComponents: [
                { id: 'fc1', name: 'Black Pearl', type: 'Gem', value: 10, productionCost: 10 },
                { id: 'fc2', name: 'Dragon Scale', type: 'Material', value: 20, productionCost: 20 },
                { id: 'fc3', name: 'Unicorn Horn', type: 'Magical', value: 50, productionCost: 50 },
                // Data from the image
                { id: 'fc_banshee_wail', name: 'Banshee Wail (captured)', type: 'Creation', value: 1, productionCost: 0 },
                { id: 'fc_dryad_bark', name: 'Dryad Bark', type: 'Creation', value: 1, productionCost: 0 },
                { id: 'fc_glacier_ice', name: 'Glacier Ice (pure)', type: 'Creation', value: 1, productionCost: 0 },
                { id: 'fc_mandrak_root', name: 'Mandrake Root', type: 'Creation', value: 2, productionCost: 0 },
                { id: 'fc_runesilver_ore', name: 'Runesilver Ore', type: 'Creation', value: 4, productionCost: 0 },
                { id: 'fc_sky_iron', name: 'Sky Iron', type: 'Creation', value: 4, productionCost: 0 },
                { id: 'fc_troll_blood', name: 'Troll Blood', type: 'Creation', value: 1, productionCost: 0 },
                { id: 'fc_deep_earth_crystal', name: 'Deep Earth Crystal', type: 'Destruction', value: 1, productionCost: 0 },
                { id: 'fc_fairy_dust', name: 'Fairy Dust', type: 'Destruction', value: 1, productionCost: 0 },
                { id: 'fc_kraken_ink', name: 'Kraken Ink', type: 'Destruction', value: 2, productionCost: 0 },
                { id: 'fc_naga_scale', name: 'Naga Scale', type: 'Destruction', value: 1, productionCost: 0 },
                { id: 'fc_sigh_of_the_wind', name: 'Sigh of the Wind', type: 'Destruction', value: 2, productionCost: 0 },
                { id: 'fc_stormshard', name: 'Stormshard', type: 'Destruction', value: 4, productionCost: 0 },
                { id: 'fc_whisper_of_time', name: 'Whisper of Time', type: 'Destruction', value: 4, productionCost: 0 },
                { id: 'fc_basilisk_eye', name: 'Basilisk Eye', type: 'Elemental', value: 1, productionCost: 0 },
                { id: 'fc_echo_of_truth', name: 'Echo of Truth', type: 'Elemental', value: 1, productionCost: 0 },
                { id: 'fc_glimmer_of_hope', name: 'Glimmer of Hope', type: 'Elemental', value: 1, productionCost: 0 },
                { id: 'fc_moondust', name: 'Moondust', type: 'Elemental', value: 2, productionCost: 0 },
                { id: 'fc_selkie_skin', name: 'Selkie Skin (shed)', type: 'Elemental', value: 2, productionCost: 0 },
                { id: 'fc_sphinx_riddle', name: 'Sphinx Riddle (solution)', type: 'Elemental', value: 4, productionCost: 0 },
                { id: 'fc_unicorn_hair', type: 'Elemental', value: 4, productionCost: 0 },
                { id: 'fc_aetherium_shard', name: 'Aetherium Shard', type: 'Power', value: 1, productionCost: 0 },
                { id: 'fc_dragon_s_scale', name: 'Dragon\'s Scale', type: 'Power', value: 1, productionCost: 0 },
                { id: 'fc_galewind_gem', name: 'Galewind Gem', type: 'Power', value: 2, productionCost: 0 },
                { id: 'fc_magma_pearl', type: 'Power', value: 2, productionCost: 0 },
                { id: 'fc_quicksilver_droplet', name: 'Quicksilver Droplet', type: 'Power', value: 2, productionCost: 0 },
                { id: 'fc_sirenstone', type: 'Power', value: 2, productionCost: 0 },
                { id: 'fc_tear_of_regret', name: 'Tear of Regret', type: 'Power', value: 4, productionCost: 0 },
                { id: 'fc_wyvern_s_bile', name: 'Wyvern\'s Bile', type: 'Power', value: 4, productionCost: 0 },
                { id: 'fc_zephyr_crystal', name: 'Zephyr Crystal', type: 'Power', value: 1, productionCost: 0 },
                { id: 'fc_dragon_s_breath_solidified', name: 'Dragon\'s Breath (solidified)', type: 'Spirit', value: 1, productionCost: 0 },
                { id: 'fc_fragment_of_silence', name: 'Fragment of Silence', type: 'Spirit', value: 1, productionCost: 0 },
                { id: 'fc_laughter_of_innocence', type: 'Spirit', value: 1, productionCost: 0 },
                { id: 'fc_phoenix_feather', name: 'Phoenix Feather', type: 'Spirit', value: 2, productionCost: 0 },
                { id: 'fc_siren_s_tear', type: 'Spirit', value: 2, productionCost: 0 },
                { id: 'fc_sunstone_fragment', type: 'Spirit', value: 4, productionCost: 0 },
                { id: 'fc_will_o_wisp_spark', name: 'Will-o\'-Wisp Spark', type: 'Spirit', value: 4, productionCost: 0 },
                { id: 'fc_blazestone_chip', name: 'Blazestone Chip', type: 'Time', value: 1, productionCost: 0 },
                { id: 'fc_emberstone', name: 'Emberstone', type: 'Time', value: 1, productionCost: 0 },
                { id: 'fc_glimmerstone_dust', name: 'Glimmerstone Dust', type: 'Time', value: 1, productionCost: 0 },
                { id: 'fc_moonpetal_bloom', name: 'Moonpetal Bloom', type: 'Time', value: 2, productionCost: 0 },
                { id: 'fc_shadow_whispers', name: 'Shadow Whispers', type: 'Time', value: 2, productionCost: 0 },
                { id: 'fc_spirit_quartz', type: 'Time', value: 4, productionCost: 0 },
                { id: 'fc_vision_of_future', name: 'Vision of Future', type: 'Time', value: 4, productionCost: 0 },
                { id: 'fc_chimera_hide', name: 'Chimera Hide', type: 'Void', value: 1, productionCost: 0 },
                { id: 'fc_essence_of_dream', name: 'Essence of Dream', type: 'Void', value: 1, productionCost: 0 },
                { id: 'fc_gryphon_claw', type: 'Void', value: 1, productionCost: 0 },
                { id: 'fc_mythical_abstract', name: 'Mythical/Abstract', type: 'Void', value: 2, productionCost: 0 },
                { id: 'fc_shard_of_memory', name: 'Shard of Memory', type: 'Void', value: 2, productionCost: 0 },
                { id: 'fc_stardew_droplet', name: 'Stardew Droplet', type: 'Void', value: 4, productionCost: 0 },
                { id: 'fc_void_obsidian', name: 'Void Obsidian', type: 'Void', value: 4, productionCost: 0 }
            ]
        };

window.potionUpdatesData = [
            { name: 'Elemental Shield', productionCost: 6, level: 6, duration: 'Indefinite', effect: 'Automatic spell defence against next elemental attack' },
            { name: 'Magic Armor', productionCost: 4, level: 4, duration: 'Indefinite', effect: 'Automatic spell defence against next physical attack' },
            { name: 'Purify Blood', productionCost: 5, level: 5, duration: 'Instant', effect: 'Removes all Alchemical/poison effects on the recipient' },
            { name: 'Reflect Magic', productionCost: 8, level: 8, duration: 'Indefinite', effect: 'Automatic spell defence against next magical attack' },
            { name: 'Remove Physical Affliction', productionCost: 6, level: 6, duration: 'Instant', effect: 'Immediately removes any active \'Physical\' effects' },
            { name: 'Release', productionCost: 5, level: 5, duration: 'Instant', effect: 'Frees the target binding effects or held by non-magical means', description: '' },
            { name: 'Remove Curse', productionCost: 7, level: 7, duration: 'Instant', effect: 'Removes the Curse spell/effect' },
            { name: 'Remove Drain', productionCost: 7, level: 7, duration: 'Instant', effect: 'Removes all active Drain spells or effects' },
            { name: 'Restore Limbs', effect: 'Removes all Withered Limb effects', productionCost: 7, expiryDate: getOneYearFromTodayDateString(), level: 7, duration: 'Instant' },
            // Removed 'Shield' potion from this update list as it's now handled by the filter
            { name: 'Shield Magic', productionCost: 5, level: 5, duration: 'Indefinite', effect: 'Automatic spell defence against next magical effect' },
            { name: 'Sleep', productionCost: 6, level: 6, duration: '5-minutes', effect: 'Victim falls into a deep sleep for 5 minutes' },
            { name: 'Taint Blood', productionCost: 5, level: 5, duration: 'Enduring', effect: 'Victim cannot run or use any in-game skills' },
            { name: 'Unparalyze', effect: 'Removes a Paralyze effect', productionCost: 8, expiryDate: getOneYearFromTodayDateString(), level: 8, duration: 'Instant' },
            { name: 'Weakness', productionCost: 3, level: 3, duration: 'Enduring', effect: 'Victim deals 5 points less damage with a weapon' },
            { name: 'Remove Weakness', productionCost: 3, level: 3, duration: 'Instant', effect: 'Removes any active Weakness effects' },
            { name: 'Wither Limb', productionCost: 7, level: 7, duration: 'Enduring', effect: 'Causes a limb to become aged, infirm, and completely useless' }
        ];

